### ISSUE TITLE
Enhancement : support package patterns on baselines

### ISSUE THREAD

**Issue by ubiratansoares** [dotanuki-labs/android-archives-watchdog#55]
Rather than listing and dumping everything we find inside an artifact, we'd like to trust a few package patterns in order to simplify the baseline with sensitive components to keep on track. 

An example of such an extension:

```toml
applicationId = "com.my.product.android"
trustedPackages = [
  "com.android.*",
  "com.my.company.*"
]

# More configuration ....
```
